version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "xml2jsonTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1szczvp0d8ca6"
s3_prefix = "xml2jsonTest"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceBucketName=\"923samsourcetest\" TargetBucketName=\"923samsourcetest-target\""
